set_property PACKAGE_PIN T10 [get_ports {SS_out[6]}]
set_property PACKAGE_PIN R10 [get_ports {SS_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {SS_out[4]}]
set_property PACKAGE_PIN K13 [get_ports {SS_out[3]}]
set_property PACKAGE_PIN P15 [get_ports {SS_out[2]}]
set_property PACKAGE_PIN T11 [get_ports {SS_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {SS_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SS_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anOut[0]}]
set_property PACKAGE_PIN U13 [get_ports {anOut[7]}]
set_property PACKAGE_PIN K2 [get_ports {anOut[6]}]
set_property PACKAGE_PIN T14 [get_ports {anOut[5]}]
set_property PACKAGE_PIN P14 [get_ports {anOut[4]}]
set_property PACKAGE_PIN J14 [get_ports {anOut[3]}]
set_property PACKAGE_PIN T9 [get_ports {anOut[2]}]
set_property PACKAGE_PIN J18 [get_ports {anOut[1]}]
set_property PACKAGE_PIN J17 [get_ports {anOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rxSerial]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property PACKAGE_PIN C4 [get_ports rxSerial]


set_false_path -from [get_ports rst]
set_false_path -from [get_ports rxSerial]
set_false_path -from [get_ports txValid]
set_false_path -from [get_ports txData[*]]
set_false_path -through [get_ports txSerial]
set_false_path -through [get_ports {SS_out[*]}]
set_false_path -through [get_ports {anOut[*]}]
create_clock -period 10.000 -name CLK -waveform {5.000 10.000} [get_ports clk]

set_property PACKAGE_PIN L16 [get_ports txValid]
set_property IOSTANDARD LVCMOS33 [get_ports txValid]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {txData[0]}]
set_property PACKAGE_PIN V10 [get_ports {txData[7]}]
set_property PACKAGE_PIN U11 [get_ports {txData[6]}]
set_property PACKAGE_PIN U12 [get_ports {txData[5]}]
set_property PACKAGE_PIN H6 [get_ports {txData[4]}]
set_property PACKAGE_PIN T13 [get_ports {txData[3]}]
set_property PACKAGE_PIN R16 [get_ports {txData[2]}]
set_property PACKAGE_PIN U8 [get_ports {txData[1]}]
set_property PACKAGE_PIN T8 [get_ports {txData[0]}]
set_property PACKAGE_PIN D4 [get_ports txSerial]
set_property IOSTANDARD LVCMOS33 [get_ports txSerial]
